name: Autoupdate pre-commit hooks

on:
  schedule:
    # Every day at 7 am
    - cron: 0 7 * * *

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
        shell: bash

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: pre-commit-${{ env.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install -U pre-commit
        shell: bash

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate --color=always
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: pre-commit-autoupdate
          title: "chore(deps): Update pre-commit hooks"
          commit-message: "chore(deps): Update pre-commit hooks"
          body: Update pre-commit hooks
          labels: dependencies,development
          delete-branch: True
